export const environment = {
  production: true,
  apiUrl: 'https://inimbleapp.com/api',
  socket: 'https://inimbleapp.com',
  url: 'https://inimbleapp.com/',
  baseWP: 'https://i-nimble.com',
  form:'https://forms.office.com/r',
  assets:'https://inimble-app.s3.us-east-1.amazonaws.com/assets/images',
  mp3: "https://inimble-app.s3.us-east-1.amazonaws.com/assets/sounds",
  upload: 'https://inimble-app.s3.us-east-1.amazonaws.com/uploads',
  stripePublicKey:'pk_live_51RoRhKPR12udsRYO3kJF97GF3NLPFrpugiDJbts3ehAfbQLzOLKsNEXKBJA2VCjw1YM9679mUjtu5WSnZkB2cUu300wKcDfj0x',
  firebaseConfig: {
    apiKey: "AIzaSyDi2g2jOi9coqrHgjF8Ojg_5mPKC1FNs1k",
    authDomain: "inimbleapp.firebaseapp.com",
    projectId: "inimbleapp",
    storageBucket: "inimbleapp.firebasestorage.app",
    messagingSenderId: "562152489018",
    appId: "1:562152489018:web:10df1fd86381626629f503"
  },
  vapidKey: 'BAgM65bd3u0eip66PuUViB9xB4agoBNFqTOragNBofHJnz7BcZM4SJqoSZyu2gj8Aiz573ExvVDwfU_eICWf2JI',
  allowedReportEmails: ['pgarcia@i-nimble.com', 'jnava@i-nimble.com', 'mfernanda@i-nimble.com'],
  allowedPaymentsEmails: ['jpalma@i-nimble.com'],
  groupCreatorEmails: ['ffernandez@i-nimble.com', 'sgutierrez@i-nimble.com'],
  allowedContentCreatorEmails: ['apalma@i-nimble.com', 'pgimmigrationservices@gmail.com', 'pete@rollwithpunch.com', 'ffernandez@i-nimble.com'],
  developmentTeamEmails: ['sgutierrez@i-nimble.com', 'ffernandez@i-nimble.com', 'sbracho@i-nimble.com', 'npena@i-nimble.com', 'adiaz@i-nimble.com'],
  rocketChatUrl: 'https://chat.inimbleapp.com',
  rocketChatWebSocketUrl: 'wss://chat.inimbleapp.com/websocket',
  rocketChatS3Bucket: 'https://inimble-chat.s3.us-east-1.amazonaws.com/f87be79d-b1cc-41f7-922b-cf132b4199fb',
  jitsiMeetUrl: 'https://meet.inimbleapp.com',
};
